Scheduler/Models/CalendarEvent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduler.Models
{
    public class CalendarEvent
    {
        public string title { get; set; }
        public DateTime start { get; set; }
        //public DateTime end { get; set; }
        public string description { get; set; }
        public string color { get; set; }
        public string textcolor { get; set; }
        public int taskid { get; set; } //not required by fullcalendar but need it to call Edit page
        public bool done { get; set; }
    }
}

Scheduler/Models/Context.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Scheduler.Models
{
    public class Context : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public Context() : base("name=Context")
        {
        }

        public System.Data.Entity.DbSet<Scheduler.Models.Task> Tasks { get; set; }
    }
}

Scheduler/Models/Task.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace Scheduler.Models
{
    public class Task
    {
        [Key]
        public int TaskId { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DueDate { get; set; }
        public bool Status { get; set; }
    }
}

Scheduler/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Scheduler.Models;
using System.Web.Script.Serialization;

namespace Scheduler.Controllers
{
    public class HomeController : Controller
    {
        private Context dbContext = new Context();
        public ActionResult Index()
        {
            List<Task> tasks = dbContext.Tasks.ToList();

            return View(tasks);
        }
        
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        //public Dictionary<User, List<Task>> GetUserTasks()
        //{
        //    var dbContext = new Context();
        //    List<User> users = dbContext.Users.ToList();
        //    var result = new Dictionary<User, List<Task>>();

        //    foreach(var user in users)
        //    {
        //        var tasksForUser = dbContext.Tasks.Where(x => x.UserId == user.UserId).ToList();
        //        result.Add(user, tasksForUser);                
        //    }

        //    return result;
        //}

        public string FetchData()
        {

            var eventList = new List<CalendarEvent>();
            foreach (Task t in dbContext.Tasks.ToList())
            {
                var eachEvent = new CalendarEvent { title = t.Title, description = t.Description, start = t.DueDate, color = "lime green", textcolor = "yellow",taskid =t.TaskId, done = t.Status};
                eventList.Add(eachEvent);
            }
            var result = GetJson(eventList);
            return GetJson(eventList);
        }
        public string GetJson(List<CalendarEvent> tasks)
        {
            return new JavaScriptSerializer().Serialize(tasks);
            
        }
    }
}

Scheduler/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Scheduler.Models;


namespace Scheduler.Controllers
{
    public class TasksController : Controller
    {
        private Context db = new Context();

        // GET: Tasks
        public ActionResult Index()
        {
            return PartialView(db.Tasks.ToList());
        }

        
        public ActionResult CreateForDate(string month, string date, string year)
        {
            var fullDate = Convert.ToDateTime(month +'/'+ date +'/'+ year);
            var task = new Task();
            task.DueDate = fullDate;
            return PartialView("Create", task);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateForDate([Bind(Include = "TaskId,Description,Title,DueDate,Status")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return PartialView(task);
        }
        // GET: Tasks/Create
        public ActionResult Create()
        {
            return PartialView("Create", new Task());

        }
        // POST: Tasks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TaskId,Description,Title,DueDate,Status")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Tasks.Add(task);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            return PartialView(task);
        }

        // GET: Tasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return PartialView(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TaskId,Description,Title,DueDate,Status")] Task task)
        {
            if (ModelState.IsValid)
            {
                db.Entry(task).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return PartialView(task);
        }

        // GET: Tasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Task task = db.Tasks.Find(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return PartialView(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Task task = db.Tasks.Find(id);
            db.Tasks.Remove(task);
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

Scheduler/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Scheduler/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Scheduler/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@model IList<Scheduler.Models.Task>

    <div id="calendar">
</div>

Scheduler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav align-right">
                    <li>@Ajax.ActionLink("Schedule","Index", "Tasks", new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace })</li>
                </ul>
            </div>
        </div>
    </div>
   
        <div class="workspace">
            @RenderBody()
        </div>

    
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div id="modal">
                </div>                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>

Scheduler/Views/Tasks/Create.cshtml
@model Scheduler.Models.Task

@{
    ViewBag.Title = "Create";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Create</h4>
</div>
<div class="modal-body">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Task</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @Value = Model.DueDate.ToString("MM/dd/yyyy"), @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Status,"Done", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Ajax.ActionLink("Back to List", "Index", "Tasks", new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace })
    </div>
  </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Scheduler/Views/Tasks/Delete.cshtml
@model Scheduler.Models.Task

@{
    ViewBag.Title = "Delete";
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Delete</h4>
</div>
<div class="modal-body">
    <h3>Are you sure you want to delete this?</h3>
    <div>       
        <hr />
        <dl class="dl-horizontal">


            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.DueDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DueDate)
            </dd>

            <dt>
                Done
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Status)
            </dd>
        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Ajax.ActionLink("Back to List", "Index", "Tasks", new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace })
            </div>
        }
    </div>
</div>


    

    

Scheduler/Views/Tasks/Edit.cshtml
@model Scheduler.Models.Task

@{
    ViewBag.Title = "Edit";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Edit</h4>
</div>
<div class="modal-body">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Task</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TaskId)



        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new {@Value =Model.DueDate.ToString("MM/dd/yyyy"), @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, "Done",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Ajax.ActionLink("Back to List", "Index", "Tasks", new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace })
    |
    @Ajax.ActionLink("Delete", "Delete", "Tasks", new { id = Model.TaskId }, new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace }, null)

</div>
</div>




    

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Scheduler/Views/Tasks/Index.cshtml
@model IEnumerable<Scheduler.Models.Task>

@{
    ViewBag.Title = "Index";
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Index</h4>
</div>
<div class="modal-body">
    <p>
        @Ajax.ActionLink("Create New", "Create", "Tasks", new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace })
    </p>
    <table class="table">
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DueDate)
            </th>
            <th>
                Done
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DueDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Ajax.ActionLink("Edit", "Edit", "Tasks", new { id = item.TaskId }, new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace }, null)
                    | @Ajax.ActionLink("Delete", "Delete", "Tasks", new { id = item.TaskId }, new AjaxOptions() { UpdateTargetId = "modal", InsertionMode = InsertionMode.Replace }, null)
                </td>
            </tr>
        }

    </table>
</div>

    

    